//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms_Casa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casa
    {
        public int Id { get; set; }
        public string Ubicacion { get; set; }
        public string Costo { get; set; }
        public string MetrosCuadrados { get; set; }
        public string DuenioAnterior { get; set; }
    }
}
